version: "3.13"

services:
  app:
    build: 
      context: ./src/app
      dockerfile: Dockerfile
    volumes:
      - ./src/app:/app
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    environment:
      - PYTHONUNBUFFERED=1
